### ISSUE TITLE
MongoDB Atlas v3.6 MongoDB Connectivity Working?

### ISSUE THREAD

**Issue by sinkr** [singer-io/tap-mongodb#42]

**Comment by sinkr** [comment]
Has anyone been able to get this to work?  I have it working for old mLab host, but cannot make it work with Python 3.6 or Python3.7 with our without dnspython and mongodb+srv or w/o in the host configuration.

Thanks for any pointers on where to look.

**Comment by sinkr** [comment]
Connectivity tests fine with the mongo CLI from the testing machine, however, if I run tap-mongodb, I get this after a circa 30 second timeout:
`./bin/tap-mongodb -c config.json --discover
CRITICAL connection closed,connection closed,connection closed
Traceback (most recent call last):
  File "./bin/tap-mongodb", line 11, in <module>
    load_entry_point('tap-mongodb==2.0.0', 'console_scripts', 'tap-mongodb')()
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/tap_mongodb/__init__.py", line 393, in main
    raise exc
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/tap_mongodb/__init__.py", line 390, in main
    main_impl()
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/tap_mongodb/__init__.py", line 377, in main_impl
    client.server_info().get('version', 'unknown'))
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/pymongo/mongo_client.py", line 1658, in server_info
    session=session)
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/pymongo/database.py", line 655, in command
    read_preference) as (sock_info, slave_ok):
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/pymongo/mongo_client.py", line 1135, in _socket_for_reads
    server = topology.select_server(read_preference)
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/pymongo/topology.py", line 226, in select_server
    address))
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/pymongo/topology.py", line 184, in select_servers
    selector, server_timeout, address)
  File "/home/ec2-user/tap-mongodb/lib64/python3.6/dist-packages/pymongo/topology.py", line 200, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed
`

**Comment by sinkr** [comment]
PEBCAK--nevermind.

**Comment by chasmfiend** [comment]
I'm seeing the same thing with Atlas, what did you end up finding?

**Comment by andrewcstewart** [comment]
@sinkr - Could you share what your issue fix was?  Did it by chance have to do with setting `ssl=true` ?

**Comment by sinkr** [comment]
> @sinkr - Could you share what your issue fix was? Did it by chance have to do with setting `ssl=true` ?

I can't really recall why at this point, but I gave up on this.   If I had to guess, I could never get Mongo as a source to adequately output to Redshift as a destination.

**Comment by parisholley** [comment]
for those stuck on this, if you go your cluster, hit "connect" button, choose standard connection, choose connection method, connect your application and choose node.js + 2.2.12 or later, it will give you the non-srv address you can use. copy the appropriate settings but use `admin` as your `database` in the tap config.
