### ISSUE TITLE
atlas (mongodb clound) doesn't connect?

### ISSUE THREAD

**Issue by zironycho** [singer-io/tap-mongodb#57]
I am used in Stitchdata.

The mongo database version is `4.2.12`.
I added four whitelist ips for stitch. 

```
2021-03-10 23:49:55,492Z   main - INFO Running tap-mongodb version 2.0.0 and target-stitch version 3.2.0
2021-03-10 23:49:55,621Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2021-03-10 23:49:55,624Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2021-03-10 23:49:55,625Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2021-03-10 23:49:55,667Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [38] at offset None
2021-03-10 23:49:55,668Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-mongodb --config /tmp/tap_discover_config.json --discover
2021-03-10 23:50:26,048Z    tap - CRITICAL xxx.yyy.mongodb.net:27017: [Errno -5] No address associated with hostname
2021-03-10 23:50:26,051Z    tap - Traceback (most recent call last):
2021-03-10 23:50:26,051Z    tap -   File "tap-env/bin/tap-mongodb", line 33, in <module>
2021-03-10 23:50:26,051Z    tap -     sys.exit(load_entry_point('tap-mongodb==2.0.0', 'console_scripts', 'tap-mongodb')())
2021-03-10 23:50:26,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_mongodb/__init__.py", line 393, in main
2021-03-10 23:50:26,051Z    tap -     raise exc
2021-03-10 23:50:26,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_mongodb/__init__.py", line 390, in main
2021-03-10 23:50:26,051Z    tap -     main_impl()
2021-03-10 23:50:26,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_mongodb/__init__.py", line 377, in main_impl
2021-03-10 23:50:26,051Z    tap -     client.server_info().get('version', 'unknown'))
2021-03-10 23:50:26,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1658, in server_info
2021-03-10 23:50:26,051Z    tap -     session=session)
2021-03-10 23:50:26,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymongo/database.py", line 655, in command
2021-03-10 23:50:26,051Z    tap -     read_preference) as (sock_info, slave_ok):
2021-03-10 23:50:26,051Z    tap -   File "/root/.pyenv/versions/3.5.2/lib/python3.5/contextlib.py", line 59, in __enter__
2021-03-10 23:50:26,051Z    tap -     return next(self.gen)
2021-03-10 23:50:26,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1135, in _socket_for_reads
2021-03-10 23:50:26,051Z    tap -     server = topology.select_server(read_preference)
2021-03-10 23:50:26,052Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymongo/topology.py", line 226, in select_server
2021-03-10 23:50:26,052Z    tap -     address))
2021-03-10 23:50:26,052Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymongo/topology.py", line 184, in select_servers
2021-03-10 23:50:26,052Z    tap -     selector, server_timeout, address)
2021-03-10 23:50:26,052Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pymongo/topology.py", line 200, in _select_servers_loop
2021-03-10 23:50:26,052Z    tap -     self._error_message(selector))
2021-03-10 23:50:26,052Z    tap - pymongo.errors.ServerSelectionTimeoutError: xxxx.yyyy.mongodb.net:27017: [Errno -5] No address associated with hostname
2021-03-10 23:50:26,579Z   main - INFO Tap exited abnormally with status 1
2021-03-10 23:50:26,650Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [15] at offset None
2021-03-10 23:50:26,651Z   main - INFO No tunnel subprocess to tear down
2021-03-10 23:50:26,651Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "xxxx.yyyy.mongodb.net:27017: [Errno -5] No address associated with hostname".
```

**Comment by mrhilton1** [comment]
FYI I managed to connect to my Atlas DB using the connection string allowed by this PR https://github.com/singer-io/tap-mongodb/pull/54/files ... hopefully it can get merged in!

**Comment by parisholley** [comment]
you can work around without #54, see my comment here

https://github.com/singer-io/tap-mongodb/issues/42#issuecomment-866379009
